repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^src/main/resources/application\.yaml$
      - id: check-json
        exclude: ^src/test/resources/malformed\.json$
      - id: check-xml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: check_format
        name: Check Java source file format
        files: ".*\\.java"
        language: system
        entry: ./mvnw spotless:check
        pass_filenames: false
