scicat:
  url: &scicat-url http://backend.localhost
  v4: false

"%it-v3":
  scicat:
    url: &scicat-url https://backend.localhost
    v4: false

"%it-v4":
  scicat:
    url: &scicat-url http://backend.localhost
    v4: true

quarkus:
  test:
    container:
      network: host
  container-image:
    build: true
    registry: ghcr.io
    group: paulscherrerinstitute
    name: scicat-rocrate
    tag: ${quarkus.application.version:latest}
  log:
    level: INFO
  http:
    root-path: /api/v1
    test-port: 9999
  rest-client:
    logging:
      scope: request-response
    scicat:
      url: *scicat-url
  smallrye-openapi:
    path: /openapi-specs
  smallrye-health:
    openapi:
      included: true
    root-path: /api/v1/health
  swagger-ui:
    path: /explorer
    always-include: true

titanium:
  jsonld:
    cache:
      size: 10
