name: CI

on:
  pull_request:
    branches: '**'

permissions:
  packages: write

env:
  devImage: ghcr.io/${{ github.repository }}-devcontainer

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      rebuildDevContainer: ${{ steps.check_changes.outputs.devcontainer_any_changed }}
      lintWorkflows: ${{ steps.check_changes.outputs.workflow_any_changed }}
      runTests: ${{ steps.check_changes.outputs.src_any_changed }}
    steps:
      - uses: actions/checkout@v6
      - name: Check for changes
        id: check_changes
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            devcontainer:
              - .devcontainer/**
            workflow:
              - .github/workflows/**
            src:
              - src/**
              - pom.xml
              - .github/workflows/ci.yaml

  build:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.rebuildDevContainer == 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          push: always

  tests:
    name: Unit + Integration tests
    needs: check_changes
    if: needs.check_changes.outputs.runTests == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: ScicatProject/scicatlive
          ref: psi/api-01/v3
          path: scicatlive

      - uses: hoverkraft-tech/compose-action@v2.5.0
        with:
          compose-file: ./compose.yaml
          cwd: ${{ github.workspace }}/scicatlive

      - name: Run test suite
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          runCmd: ./mvnw verify -DskipITs=false -Dquarkus.container-image.push=false

  actionlint:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.lintWorkflows == 'true'
    steps:
      - uses: actions/checkout@v6
      - name: Lint workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  precommit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: pre-commit
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: ${{ env.devImage }}
          cacheFrom: ${{ env.devImage }}
          runCmd: pre-commit run --all-files
